
suite = testsuite(["testBlackCall.m","testRateIntegral.m",...
                   'testFwdSpot.m','testFwdSpot.m','testSmileVol.m','testVol.m',...
                   'testPdf.m','testEuropean.m']);

runner = matlab.unittest.TestRunner.withTextOutput('OutputDetail', matlab.unittest.Verbosity.Detailed);

import matlab.unittest.plugins.TestReportPlugin 
runner.addPlugin(TestReportPlugin.producingPDF("autogeneratedTestReport.pdf"));  %generate report


result = runner.run(suite);
disp(result);
 